FROM microsoft/windowsservercore:1607

ENV hugo_download_url   "https://github.com/gohugoio/hugo/releases/download/v0.83.1/hugo_extended_0.83.1_Windows-64bit.zip"
ENV azcopy_download_url "https://aka.ms/downloadazcopy-v10-windows"
ENV azcli_download_url  "https://aka.ms/installazurecliwindows"

# Use Powershell
SHELL ["powershell", "-Command", "$ErrorActionPreference = 'Stop'; $ProgressPreference = 'SilentlyContinue';"]

# Get Downloads
RUN [Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12 ; \
    [System.Net.WebRequest]::DefaultWebProxy.Credentials = [System.Net.CredentialCache]::DefaultCredentials ; \
    mkdir c:\kits ; \
    cd c:\kits ; \
    Invoke-WebRequest -Uri $env:hugo_download_url   -OutFile c:\kits\hugo.zip ; \
    Invoke-WebRequest -Uri $env:azcopy_download_url -OutFile c:\kits\azcopy_v10.zip ; \
    Invoke-WebRequest -Uri $env:azcli_download_url   -OutFile c:\kits\AzureCLI.msi;

# Install Hugo
RUN Expand-Archive -LiteralPath 'c:\kits\hugo.zip' -DestinationPath 'c:\kits\' -Force ; \
    rm c:\kits\hugo.zip ; \
    mv 'c:\kits\hugo.exe' 'C:\Windows\system32\hugo.exe' ; \
    hugo version

# Install az cli for pushing build to Azure storage blob
RUN Start-Process msiexec.exe -Wait -ArgumentList '/I c:\kits\AzureCLI.msi /quiet'; \
    rm c:\kits\AzureCLI.msi ; \
    az version;

# Install azcopy to copy site to blob storage later
RUN Expand-Archive -LiteralPath 'c:\kits\azcopy_v10.zip' -DestinationPath 'c:\kits\' ; \
    rm c:\kits\azcopy_v10.zip ; \
    mv 'c:\kits\azcopy_windows_amd64_10.10.0\azcopy.exe' 'C:\Windows\system32\azcopy10.exe' ; \
    azcopy --version

EXPOSE 1313
