name: Build-Dockerfile-and-Push-to-Registry

# Controls when the action will run.  In this case only if the Dockerfile changes
on:
  push:
    branches: [ draft ]
    paths:
      - 'Dockerfile'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y%m%d')"

      - name: build and push to dockerhub and initiate deploment
        env:
          DOCKERHUBUSERNAME: ${{ secrets.DOCKERHUBUSERNAME }}
          DOCKERHUBPASSWORD: ${{ secrets.DOCKERHUBPASSWORD }}
        run: |
          docker login --username $DOCKERHUBUSERNAME --password $DOCKERHUBPASSWORD
          docker build . -t iaingblack/rootisgod-builder:latest
          docker tag iaingblack/rootisgod-builder:latest iaingblack/rootisgod-builder:${{ steps.date.outputs.date }}
          docker push iaingblack/rootisgod-builder:latest
          docker push iaingblack/rootisgod-builder:${{ steps.date.outputs.date }}