# This is a basic workflow to help you get started with Actions

name: Build-Dockerfile-and-Push-to-Registry

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ draft ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - name: Build and Publish Dockerfile
        # You may pin to the exact commit or the version.
        # uses: ryanjfrizzell/action-bpd@7d6d0456081acbdbe2adeae5da1d14f1a0e54498
        uses: ryanjfrizzell/action-bpd@v1.0.2
        with:
          # the url your registry is located at, used for docker login, ex: docker.pkg.github.com
          docker_registry_url: # default is 
          # the owner for the registry, ex: ryanjfrizzell
          docker_registry_owner: # default is 
          # repository of the image, ex: action-bpd  
          docker_repository: # default is 
          # image name to use
          docker_image: iaingblack/rootisgod-builder
          docker_username: 
          docker_password: 
          dockerhub: true
      
      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
