# This is a basic workflow to help you get started with Actions

name: Build-Dockerfile-and-Push-to-Registry

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ draft ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - name: build and push to dockerhub and initiate deploment
        env:
          DOCKERHUBUSERNAME: ${{ secrets.DOCKERHUBUSERNAME }}
          DOCKERHUBPASSWORD: ${{ secrets.DOCKERHUBPASSWORD }}
        uses: yokiworks/deploy-github-action@1.0.10
        with:
          # The docker container image name
          image-name: iaingblack/rootisgod-builder:latest
          # The dockerfile used by the docker build command
          docker-file: Dockerfile
          # Dockerhub username
          dockerhub-username: $DOCKERHUBUSERNAME
          # Dockerhub password
          dockerhub-password: $DOCKERHUBPASSWORD
