# This is a basic workflow to help you get started with Actions

name: LIVE

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the draft branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ draft ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    container:
      image: iaingblack/rootisgod-builder:latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Install Required Gems and Show Jekyll Version
        run: |
          bundle install
          bundle exec jekyll -v

      - name: Build Site
        run: |
          bundle exec jekyll build

      - name: Sync Site Files to Site
        env:
          LIVESTORAGEACCOUNTANDSASTOKEN: ${{ secrets.LIVESTORAGEACCOUNTANDSASTOKEN }}
        run: |
          azcopy10 sync "./_site/" "$LIVESTORAGEACCOUNTANDSASTOKEN" --delete-destination true
    
      - name: Purge CDN Cache
        env:
          LIVESPSECRET: ${{ secrets.LIVESPSECRET }}
        run: |
          az login --service-principal --username "bda99ed3-1b04-4a7a-9b6c-ee3d371c5553" --password "$LIVESPSECRET" --tenant "faa9681f-25c0-459c-95c2-d2e8607e1b72"
          az cdn endpoint purge --resource-group "www.rootisgod.com" --name "rootisgod" --profile-name "rootisgod-cdn" --content-paths "/*"
        
