# Pushes non-master branch changes to https://draft.rootisgod.com/

name: DRAFT

# Controls when the action will run.
on:
    # Triggers the workflow on push or pull request events
    push:
        branches: [draft]

    # Allows you to run this workflow manually from the Actions tab
    workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
    # This workflow contains a single job called "build"
    build:
        # The type of runner that the job will run on
        runs-on: ubuntu-latest
        container:
            image: iaingblack/rootisgod-builder:latest

        # Steps represent a sequence of tasks that will be executed as part of the job
        steps:
            # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
            - uses: actions/checkout@v2

            - name: Build Site
              run: |
                  hugo -e draft

            - name: Sync Site Files to Site
              env:
                  DRAFTSTORAGEACCOUNTANDSASTOKEN: ${{ secrets.DRAFTSTORAGEACCOUNTANDSASTOKEN }}
              run: |
                  azcopy10 sync "./public/" "$DRAFTSTORAGEACCOUNTANDSASTOKEN" --delete-destination true
